apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-nest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-nest
  template:
    metadata:
      labels:
        app: api-nest
    spec:
      containers:
        - name: api-nest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-api-nest-config
