replicaCount: 2
image:
  repository: elara/api-nest
  tag: production
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 3001
apiAiPort: 80
secrets:
  enabled: true
  name: elara-secrets
ingress:
  enabled: true
  className: nginx
  host: elara.app
  path: /api
  pathType: Prefix
  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod
    secretName: elara-tls-api-nest
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
autoscaling:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi
env:
  ENVIRONMENT: production