apiVersion: v1
kind: Secret
metadata:
  name: elara-secrets
  namespace: elara-prod
type: Opaque
stringData:
  # À remplacer par les vraies valeurs en prod ou via SOPS/Vault
  DATABASE_URL: "postgresql://postgres:password@db-host:5432/elara?schema=public"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  AUTH_SECRET: "super-secret-key-for-next-auth"
